name: Go

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:

  ## TODO: Ideally test this before releasing, but that's technically handled in the separate workflow..
  deploy:
    name: Release
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Build and publish in parallel:
        # linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Build Information
        run: |
          # echo "SHOELACES_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
          echo "SHOELACES_VERSION=${{ env.GITHUB_REF_NAME }}" >> $GITHUB_ENV
          echo "SHOELACES_BUILD=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "SHOELACES_BUILD_SHORT=$(date -u +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Build and Release
        uses: wangyoucao577/go-release-action@v1.29
        # if: ${{ github.ref_type == 'tag' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: shoelaces-${{ env.SHOELACES_BUILD_SHORT }}-${{ matrix.goos }}-${{ matrix.goarch }}
          extra_files: LICENSE README.md CHANGELOG.md
          # build_command: packr2 build
          ldflags: -X main.version=${{ env.SHOELACES_VERSION }} -X main.build=${{ env.SHOELACES_BUILD }}
          # release_tag: ${{ env.SHOELACES_VERSION }}

      # # https://github.com/actions/setup-go
      # - name: Setup Go
      #   uses: actions/setup-go@v3
      #   with:
      #     ## TODO: Should we just always use the latest version of Go?
      #     # go-version: 1.18
      #     # check-latest: false
      #     check-latest: true
      #     cache: true

      # ## TODO: Shouldn't we build for ALL supported architectures,
      # ##       considering we want to release binaries for them anyway?
      # ## TODO: Only build for the active architecture?
      # - name: Build
      #   # run: make build
      #   run: |
      #     go version
      #     go build -v ./...

      # ## TODO: Only release for tagged/versioned releases?
      # - name: Release
      #   uses: go-semantic-release/action@v1.18.0
      #   if: ${{ github.event_name != 'pull_request' }}
      #   ## TODO: Configure appropriately for production vs. pre-release etc.
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
